### ISSUE TITLE
White Screen HoloLens2

### ISSUE THREAD

**Issue by JorgeZehl** [EnoxSoftware/HoloLensCameraStream#2]
I was not able to run the plugin with HoloLens2 and unity 2020.3.41f1. I get the following error:

Assets "CamStreamStream" Example "VideoPanelApp.cs(61,39): error CS0234: The type or namespace name 'WorldManager' does not exist in the namespace 'UnityEngine.XR.WSA' (are you missing an assembly reference?).

the workaround I implemented was to replace:

` _spatialCoordinateSystemPtr = UnityEngine.XR.WSA.WorldManager.GetNativeISpatialCoordinateSystemPtr();
with the following line of code `

`_spatialCoordinateSystemPtr = Microsoft.MixedReality.Toolkit.WindowsMixedReality.WindowsMixedRealityUtilities.UtilitiesProvider.ISpatialCoordinateSystemPtr;`
i try also:
[I also tried using this solution from another post](https://github.com/EnoxSoftware/HoloLensWithOpenCVForUnityExample/issues/32#issuecomment-941873594)

I was able to compile the code without errors but when viewing the panel I only see a white screen. I urgently need to use this plugin I would be eternally grateful if someone could help me. As a clarification when starting the application I get a pop to allow the use of the camera. The problem is in the camera permissions.

**Comment by EnoxSoftware** [comment]
We have done a lot of testing on a Unity version (2020.3.38f1) that is close to your development environment.

Is the project set up as described in the README?
https://xn--github-oz1ll283a.com/EnoxSoftware/HoloLensCameraStream#running-the-example-unity-project
In particular, the following process

> Add Define Symbols: Open File > Build Settings > Player Settings > Other Settings and add the following to Scripting Define Symbols depending on the XR system used in your project; Legacy built-in XR: BUILTIN_XR'; XR Plugin Management (Windows Mixed Reality): XR_PLUGIN_WINDOWSMR; XR Plugin Management (OpenXR):XR_PLUGIN_OPENXR.


In addition, you may find this setup procedure helpful.
https://github.com/EnoxSoftware/HoloLensWithOpenCVForUnityExample#setup


It is normal for the camera usage permission pop-up to appear immediately after the application is launched.
For camera permissions, it is fine as long as "WebCam" Capabilties is enabled in the Publication Settings tab.
Normally, by granting permission, the camera image will be displayed.

**Comment by JorgeZehl** [comment]
Indeed the error was that I used the define BUILTIN_XR instead of using XR_PLUGIN_OPENXR. That solved the problem
